server:
  port: 8081
  shutdown: graceful

spring:
  application:
    name: monitoring-app


  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: monitoring-app-${random.uuid}
      auto-offset-reset: earliest
      properties:
        spring.json.use.type.headers: false

management:
  server:
    port: 9101
  endpoints:
    web:
      exposure:
        include: health, prometheus
      base-path: "/"
      path-mapping:
        prometheus: "metrics"
  metrics:
    tags:
      application: monitoring-app
